# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ['main']

jobs:
  build:
    #configurando o container que será utilizado
    runs-on: ubuntu-latest

    steps:
      # baixando o código do container
      - uses: actions/checkout@v3
      # instalando a versão python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      # Lint => pluggin wemake-python-styleguide
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
        with:
          path: 'src'
      # fazendo os testes
      - name: Test with pytest
        run: |
          pytest

  deploy:
    #configurando o container que será utilizado
    runs-on: ubuntu-latest
    # configurando para rodar somente apos o step:build finalizar
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
